name: Deploy Online Boutique

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1 
      with:
        registry: us-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCR_SA_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: us-docker.pkg.dev/online-boutique-ci/charts/onlineboutique:latest
        load: true

    - name: Install Helm
      run: |
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor > helm.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=helm.gpg] https://baltocdn.com/stable/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/helm-stable-debian.list
        apt-get update && apt-get install helm

    - name: Configure Helm
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update

    - name: Deploy with Helm
      run: |
        helm upgrade onlineboutique oci://us-docker.pkg.dev/online-boutique-ci/charts/onlineboutique --install
